SELECT CAR_ID,
        ROUND(
            SUM(END_DATE-START_DATE+1)/COUNT(CAR_ID), 1) as AVERAGE_DURATION
        
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    HAVING SUM(END_DATE-START_DATE+1)/COUNT(CAR_ID) >= 7
    GROUP BY CAR_ID
    
    ORDER BY AVERAGE_DURATION desc, CAR_ID desc