SELECT TITLE, b.BOARD_ID, REPLY_ID, r.WRITER_ID, r.CONTENTS, to_char(r.CREATED_DATE,'yyyy-mm-dd')

FROM USED_GOODS_BOARD b 
    INNER JOIN USED_GOODS_REPLY r
    ON b.BOARD_ID = r.BOARD_ID
    WHERE to_char(b.CREATED_DATE, 'YYYY-mm' ) = '2022-10'

    ORDER BY r.CREATED_DATE, b.TITLE