SELECT  EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) HOUR , count(*) COUNT
FROM ANIMAL_OUTS 
    WHERE to_char(DATETIME, 'HH24') BETWEEN '09' AND '19'
        GROUP BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
        ORDER BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))