SELECT i.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
, ROUND(AVG(REVIEW_SCORE), 2)

FROM REST_INFO i
    INNER JOIN REST_REVIEW r
    ON i.REST_ID = r.REST_ID

    WHERE ADDRESS LIKE '¼­¿ï%' 
    GROUP BY i.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS

    ORDER BY AVG(REVIEW_SCORE) desc, FAVORITES desc