SELECT EXTRACT(YEAR FROM SALES_DATE) as YEAR,
        EXTRACT(MONTH FROM SALES_DATE) as MONTH,
        COUNT(DISTINCT u.USER_ID) as PUCHASED_USERS,
        ROUND(COUNT(DISTINCT u.USER_ID) / 
            (SELECT COUNT(USER_ID)
                FROM USER_INFO 
                WHERE EXTRACT(YEAR FROM JOINED) = '2021'), 1)
                as PUCHASED_RATIO
        
FROM USER_INFO u
    INNER JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
    -- 2021년에 가입했으며 구매한 이력이 있는 회원
    WHERE EXTRACT(YEAR FROM JOINED) = '2021'
    AND EXISTS (SELECT 1 
                FROM ONLINE_SALE)
    
    -- 중복 제거
    GROUP BY EXTRACT(YEAR FROM SALES_DATE),
        EXTRACT(MONTH FROM SALES_DATE)
        
    -- 정렬
    ORDER BY YEAR, MONTH